name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04.5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.22.9'

      - name: Install dependencies and test
        run: |
          npm install
          npm test

      - name: Deploy to server
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd /path/to/your/project
            git pull origin main
            npm install
            npm run build
            pm2 restart server
          EOF
